### PR TITLE
Sort activities by recorder unit IDs in Insite mode

### LINKED ISSUE #367: Color mismatch with Insite
**Describe the bug**
The color in the activity is not matched with one in the network configuration.

**To Reproduce**
Simulate with Insite. We have 800 red neurons and 200 blue neurons 
but in raster plot, these colors are swapped (See screenshot below).

**Expected behavior**
Color of activity should match with color indicator of the network.

**Screenshots**
screenshot-localhost_8001-2022 05 31-15_01_50

### PR DESCRIPTION
**Pull request by babsey**
This PR fixed color mismatch of activities in Insite mode by sorting activities by recorder unit IDs.

Thus, I renamed `nodeCollectionId` to `recorderUnitId`.

Fixed #367

### CODE REVIEW

File: src/core/project/insite/insite.ts [hunk 1]
```diff
@@ -196,12 +196,17 @@ export class Insite {
...
           return {
             events: { senders: [], times: [] },
-            nodeCollectionId: data.spikerecorderId,
+            recorderUnitId: data.spikerecorderId,
             nodeIds: data.nodeIds,
             nodePositions,
           };
         });
 
+        // Sort activities by recorder unit ids.
```
Comment (jens-br) [inline src/core/project/insite/insite.ts:205]:
```suggestion
        // Sort activities by recorder unit IDs, as Insite does not provide a sorting at the moment.
```

File: src/core/project/insite/insite.ts [hunk 2]
```diff
@@ -246,12 +251,17 @@ export class Insite {
...
           return {
             events,
-            nodeCollectionId: data.multimeterId,
+            recorderUnitId: data.multimeterId,
             nodeIds: data.nodeIds,
             nodePositions,
           };
         });
 
+        // Sort activities by recorder unit ids.
```
Comment (jens-br) [inline src/core/project/insite/insite.ts:260]:
```suggestion
        // Sort activities by recorder unit IDs, as Insite does not provide a sorting at the moment.
```

**Review by jens-br — CHANGES_REQUESTED** [review]
Looks good, only a minor extension of the explanations suggested.

File: src/core/project/insite/insite.ts [hunk 3]
```diff
@@ -196,12 +196,17 @@ export class Insite {
...
           return {
             events: { senders: [], times: [] },
-            nodeCollectionId: data.spikerecorderId,
+            recorderUnitId: data.spikerecorderId,
             nodeIds: data.nodeIds,
             nodePositions,
           };
         });
 
+        // Sort activities by recorder unit IDs, as Insite does not provide a sorting at the moment.
```
Comment (jens-br) [inline src/core/project/insite/insite.ts:205]:
```suggestion
        // Sort activities by recorder unit IDs, as Insite does not provide a sorting at the moment. TODO: check in the future
```

File: src/core/project/insite/insite.ts [hunk 4]
```diff
@@ -246,12 +251,17 @@ export class Insite {
...
           return {
             events,
-            nodeCollectionId: data.multimeterId,
+            recorderUnitId: data.multimeterId,
             nodeIds: data.nodeIds,
             nodePositions,
           };
         });
 
+        // Sort activities by recorder unit IDs, as Insite does not provide a sorting at the moment.
```
Comment (jens-br) [inline src/core/project/insite/insite.ts:260]:
```suggestion
        // Sort activities by recorder unit IDs, as Insite does not provide a sorting at the moment. TODO: check in the future
```

**Review by jens-br — COMMENTED** [review]
Small addition to include the latest info from Marcel

**Review by jens-br — APPROVED** [review]
LGTM :+1:
